### ISSUE TITLE
Field "status" of type Optional[ChargingStatus] in Charging has invalid value

### ISSUE THREAD

**Issue by sonar98** [skodaconnect/homeassistant-myskoda#64]
When restarting Home Assitant while the car is not charging the Myskoda integration won't initialize.

````
Logger: myskoda.rest_api
Bron: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:43
Eerst voorgekomen: 20:54:13 (55 gebeurtenissen)
Laatst gelogd: 22:10:03

Failed to load data from url /v1/charging/TMXXXXXXXXXXX. Return value was '{"isVehicleInSavedLocation":false,"status":{"chargingRateInKilometersPerHour":0.0,"chargePowerInKw":0.0,"remainingTimeToFullyChargedInMinutes":0,"battery":{"remainingCruisingRangeInMeters":251000,"stateOfChargeInPercent":65}},"settings":{"targetStateOfChargeInPercent":70,"preferredChargeMode":"MANUAL","availableChargeModes":["MANUAL"],"chargingCareMode":"ACTIVATED","autoUnlockPlugWhenCharged":"OFF","maxChargeCurrentAc":"MAXIMUM","batterySupport":"DISABLED"},"carCapturedTimestamp":"2024-10-02T15:26:54Z","errors":[{"type":"STATUS_OF_CHARGING_NOT_AVAILABLE","description":"Status of charging is not available."}]}'
Traceback (most recent call last):
  File "<string>", line 24, in __mashumaro_from_json__
  File "<string>", line 14, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "state" of type ChargingState is missing in ChargingStatus instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 26, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "status" of type Optional[ChargingStatus] in Charging has invalid value {'chargingRateInKilometersPerHour': 0.0, 'chargePowerInKw': 0.0, 'remainingTimeToFullyChargedInMinutes': 0, 'battery': {'remainingCruisingRangeInMeters': 251000, 'stateOfChargeInPercent': 65}}
````

````
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.myskoda.coordinator
Bron: helpers/update_coordinator.py:354
integratie: MySkoda (documentatie, problemen)
Eerst voorgekomen: 20:54:13 (55 gebeurtenissen)
Laatst gelogd: 22:10:03

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "<string>", line 24, in __mashumaro_from_json__
  File "<string>", line 14, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "state" of type ChargingState is missing in ChargingStatus instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 82, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 222, in get_vehicle
    vehicle.charging = await self.get_charging(vin)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 163, in get_charging
    return await self.rest_api.get_charging(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 59, in get_charging
    return await self._make_get_request(f"/v1/charging/{vin}", Charging.from_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 26, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "status" of type Optional[ChargingStatus] in Charging has invalid value {'chargingRateInKilometersPerHour': 0.0, 'chargePowerInKw': 0.0, 'remainingTimeToFullyChargedInMinutes': 0, 'battery': {'remainingCruisingRangeInMeters': 251000, 'stateOfChargeInPercent': 65}}

**Comment by WebSpider** [comment]
Thanks for our report!
What version of the integration / library are you running?

**Comment by sonar98** [comment]
version 1.4.2

**Comment by WebSpider** [comment]
Summary:

`state` field in charing info is missing when error `STATUS_OF_CHARGING_NOT_AVAILABLE` is present. 

Thanks!

**Comment by WebSpider** [comment]
This is fixed in https://github.com/skodaconnect/myskoda/pull/47 and will be in the next release.

**Comment by WebSpider** [comment]
Duplicate of #36

**Comment by dvx76** [comment]
Not fixed. `ChargingStatus.state` needs to default to `None`, not just allow `None`.
